version: "3"

networks:
  default:
    name: social-net

services:
  consul:
    image: consul

  db1:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db1
    hostname: db1
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 65hh0x21GJmlqM
      MYSQL_USER: social-network-user
      MYSQL_PASSWORD: sQ7mDXwwLcfq
      MYSQL_DATABASE: social-network
    command: ["mysqld",
              "--log-bin",
              "--binlog-format=ROW",
              "--server-id=1",
              "--gtid-mode=ON",
              "--enforce-gtid-consistency=ON",
              "--plugin-load-add=group_replication.so",
              "--relay-log-recovery=ON",
              "--loose-group-replication-start-on-boot=OFF",
              "--loose-group-replication-group-name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
              "--loose-group-replication-local-address=db1:33061",
              "--loose-group-replication-group-seeds=db1:33061,db2:33061,db3:33061",
              "--loose-group_replication_bootstrap_group=OFF"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  db2:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db2
    hostname: db2
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 65hh0x21GJmlqM
      MYSQL_USER: social-network-user
      MYSQL_PASSWORD: sQ7mDXwwLcfq
      MYSQL_DATABASE: social-network
    command: ["mysqld",
              "--log-bin",
              "--binlog-format=ROW",
              "--server-id=2",
              "--gtid-mode=ON",
              "--enforce-gtid-consistency=ON",
              "--plugin-load-add=group_replication.so",
              "--relay-log-recovery=ON",
              "--loose-group-replication-start-on-boot=OFF",
              "--loose-group-replication-group-name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
              "--loose-group-replication-local-address=db2:33061",
              "--loose-group-replication-group-seeds=db1:33061,db2:33061,db3:33061",
              "--loose-group_replication_bootstrap_group=OFF"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  db3:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db3
    hostname: db3
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 65hh0x21GJmlqM
      MYSQL_USER: social-network-user
      MYSQL_PASSWORD: sQ7mDXwwLcfq
      MYSQL_DATABASE: social-network
    command: ["mysqld",
              "--log-bin",
              "--binlog-format=ROW",
              "--server-id=3",
              "--gtid-mode=ON",
              "--enforce-gtid-consistency=ON",
              "--plugin-load-add=group_replication.so",
              "--relay-log-recovery=ON",
              "--loose-group-replication-start-on-boot=OFF",
              "--loose-group-replication-group-name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
              "--loose-group-replication-local-address=db3:33061",
              "--loose-group-replication-group-seeds=db1:33061,db2:33061,db3:33061",
              "--loose-group_replication_bootstrap_group=OFF"]
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  dialogue1:
    image: postgres
    container_name: dialogue1
    hostname: dialogue1
    restart: unless-stopped
    environment:
      POSTGRES_USER: dialogue-user
      POSTGRES_PASSWORD: pG7mDXwwLcfq
      POSTGRES_DB: dialogue
    depends_on:
      - counter
      - mq
      - consul

  dialogue2:
    image: postgres
    container_name: dialogue2
    hostname: dialogue2
    restart: unless-stopped
    environment:
      POSTGRES_USER: dialogue-user
      POSTGRES_PASSWORD: pG7mDXwwLcfq
      POSTGRES_DB: dialogue
    depends_on:
      - counter
      - mq
      - consul

  mq:
    image: rabbitmq
    container_name: mq
    hostname: mq
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: unless-stopped

  counter:
    build: ./counter-service
    ports:
      - "7003:80"
    restart: unless-stopped
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_SERVICE_ID=dialogues2
    depends_on:
      - mq
      - consul
      - redis

  dialogues:
    build: ./dialogue-service
    ports:
      - "7001:80"
    restart: unless-stopped
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_SERVICE_ID=dialogues
      - INIT_DB=true
    depends_on:
      - dialogue1
      - dialogue2
      - consul

  dialogues2:
    build: ./dialogue-service
    ports:
      - "7002:80"
    restart: unless-stopped
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_SERVICE_ID=dialogues2
    depends_on:
      - dialogue1
      - dialogue2
      - consul

  service1:
    build: ./main
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - db1
      - db2
      - db3
      - dialogues
      - dialogues2
      - mq
      - consul
      - counter

  service2:
    build: ./main
    restart: unless-stopped
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - db1
      - db2
      - db3
      - dialogues
      - dialogues2
      - mq
      - consul
      - counter

  service3:
    build: ./main
    restart: unless-stopped
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - db1
      - db2
      - db3
      - dialogues
      - dialogues2
      - mq
      - consul
      - counter

  nginx:
    image: nginx:1.21
    container_name: nginx-lb
    restart: on-failure
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
      - "8080:8080"

  haproxy:
    image: haproxy:2.4
    restart: on-failure
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
